Route102_EventScript_ItemPotion:: @ 8290CD8
	finditem ITEM_LUCARIONITE
	end

Route103_EventScript_ItemGuardSpec:: @ 8290CE5
	finditem ITEM_NET_BALL
	end

Route103_EventScript_ItemPPUp:: @ 8290CF2
	finditem ITEM_ZAP_PLATE
	end

Route104_EventScript_ItemPPUp:: @ 8290CFF
	finditem ITEM_REVIVE
	end

Route104_EventScript_ItemPokeBall:: @ 8290D0C
	finditem ITEM_HYPER_POTION
	end

Route104_EventScript_ItemXAccuracy:: @ 8290D19
	finditem ITEM_CHARCOAL
	end

Route104_EventScript_ItemPotion:: @ 8290D26
	finditem ITEM_YELLOW_NECTAR
	end

Route105_EventScript_ItemIron:: @ 8290D33
	finditem ITEM_RABUTA_BERRY
	end

Route106_EventScript_ItemProtein:: @ 8290D40
	finditem ITEM_MAX_REPEL
	end

Route108_EventScript_ItemStarPiece:: @ 8290D4D
	finditem ITEM_SPELON_BERRY
	end

Route109_EventScript_ItemPPUp:: @ 8290D5A
	finditem ITEM_INSECT_PLATE
	end

Route109_EventScript_ItemPotion:: @ 8290D67
	finditem ITEM_LEVEL_BALL
	end

Route110_EventScript_ItemRareCandy:: @ 8290D74
	finditem ITEM_METAL_COAT
	end

Route110_EventScript_ItemDireHit:: @ 8290D81
	finditem ITEM_CLEVER_WING
	end

Route110_EventScript_ItemElixir:: @ 8290D8E
	finditem ITEM_CLEVER_WING
	end

Route111_EventScript_ItemTM37:: @ 8290D9B
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust:: @ 8290DA8
	finditem ITEM_STEEL_GEM
	end

Route111_EventScript_ItemHPUp:: @ 8290DB5
	finditem ITEM_YELLOW_SCARF
	end

Route111_EventScript_ItemElixir:: @ 8290DC2
	finditem ITEM_SHINY_STONE
	end

Route112_EventScript_ItemNugget:: @ 8290DCF
	finditem ITEM_RAZZ_BERRY
	end

Route113_EventScript_ItemMaxEther:: @ 8290DDC
	finditem ITEM_ELIXIR
	end

Route113_EventScript_ItemSuperRepel:: @ 8290DE9
	finditem ITEM_WHITE_HERB
	end

Route113_EventScript_ItemHyperPotion:: @ 8290DF6
	finditem ITEM_NEVER_MELT_ICE
	end

Route114_EventScript_ItemRareCandy:: @ 8290E03
	finditem ITEM_PSYCHIC_SEED
	end

Route114_EventScript_ItemProtein:: @ 8290E10
	finditem ITEM_NET_BALL
	end

Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
	finditem ITEM_FIGHTING_GEM
	end

Route115_EventScript_ItemSuperPotion:: @ 8290E2A
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemTM01:: @ 8290E37
	finditem ITEM_TM01
	end

Route115_EventScript_ItemIron:: @ 8290E44
	finditem ITEM_ALAKAZITE
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	finditem ITEM_FIRE_STONE
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	finditem ITEM_FIRE_STONE
	end

Route115_EventScript_ItemPPUp:: @ 8290E6B
	finditem ITEM_ICE_HEAL
	end

Route116_EventScript_ItemXSpecial:: @ 8290E78
	finditem ITEM_FAIRY_MEMORY
	end

Route116_EventScript_ItemEther:: @ 8290E85
	finditem ITEM_LUSTROUS_ORB
	end

Route116_EventScript_ItemRepel:: @ 8290E92
	finditem ITEM_HARBOR_MAIL
	end

Route116_EventScript_ItemHPUp:: @ 8290E9F
	finditem ITEM_HONEY
	end

Route116_EventScript_ItemPotion:: @ 8290EAC
	finditem ITEM_SCEPTILITE
	end

Route117_EventScript_ItemGreatBall:: @ 8290EB9
	finditem ITEM_AERODACTYLITE
	end

Route117_EventScript_ItemRevive:: @ 8290EC6
	finditem ITEM_TIMER_BALL
	end

Route118_EventScript_ItemHyperPotion:: @ 8290ED3
	finditem ITEM_MAX_REVIVE
	end

Route119_EventScript_ItemSuperRepel:: @ 8290EE0
	finditem ITEM_GHOST_GEM
	end

Route119_EventScript_ItemZinc:: @ 8290EED
	finditem ITEM_QUALOT_BERRY
	end

Route119_EventScript_ItemElixir:: @ 8290EFA
	finditem ITEM_ELECTRIC_GEM
	end

Route119_EventScript_ItemLeafStone:: @ 8290F07
	finditem ITEM_WATMEL_BERRY
	end

Route119_EventScript_ItemRareCandy:: @ 8290F14
	finditem ITEM_CHARIZARDITE_Y
	end

Route119_EventScript_ItemHyperPotion:: @ 8290F21
	finditem ITEM_SALAC_BERRY
	end

Route119_EventScript_ItemHyperPotion2:: @ 8290F2E
	finditem ITEM_SALAC_BERRY
	end

Route119_EventScript_ItemElixir2:: @ 8290F3B
	finditem ITEM_LUM_BERRY
	end

Route120_EventScript_ItemNugget:: @ 8290F48
	finditem ITEM_ROSE_INCENSE
	end

Route120_EventScript_ItemFullHeal:: @ 8290F55
	finditem ITEM_RED_SCARF
	end

Route120_EventScript_ItemHyperPotion:: @ 8290F62
	finditem ITEM_CUSTAP_BERRY
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	finditem ITEM_MEWTWONITE_X
	end

Route120_EventScript_ItemRevive:: @ 8290F7C
	finditem ITEM_STEEL_GEM
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	finditem ITEM_PRETTY_WING
	end

Route121_EventScript_ItemRevive:: @ 8290F96
	finditem ITEM_SAFETY_GOGGLES
	end

Route121_EventScript_ItemZinc:: @ 8290FA3
	finditem ITEM_METAL_POWDER
	end

Route123_EventScript_ItemCalcium:: @ 8290FB0
	finditem ITEM_ROCKY_HELMET
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	finditem ITEM_AERODACTYLITE
	end

Route123_EventScript_ItemElixir:: @ 8290FCA
	finditem ITEM_SUPER_REPEL
	end

Route123_EventScript_ItemPPUp:: @ 8290FD7
	finditem ITEM_SHOCK_DRIVE
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	finditem ITEM_ODD_INCENSE
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	finditem ITEM_PURPLE_NECTAR
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	finditem ITEM_LEMONADE
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	finditem ITEM_LEPPA_BERRY
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	finditem ITEM_POISON_BARB
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	finditem ITEM_HP_UP
	end

Route127_EventScript_ItemZinc:: @ 8291032
	finditem ITEM_DREAM_BALL
	end

Route127_EventScript_ItemCarbos:: @ 829103F
	finditem ITEM_REVIVE
	end

Route127_EventScript_ItemRareCandy:: @ 829104C
	finditem ITEM_TOXIC_PLATE
	end

Route132_EventScript_ItemRareCandy:: @ 8291059
	finditem ITEM_TWISTED_SPOON
	end

Route132_EventScript_ItemProtein:: @ 8291066
	finditem ITEM_ELIXIR
	end

Route133_EventScript_ItemBigPearl:: @ 8291073
	finditem ITEM_LATIASITE
	end

Route133_EventScript_ItemStarPiece:: @ 8291080
	finditem ITEM_BLUE_SHARD
	end

Route133_EventScript_ItemMaxRevive:: @ 829108D
	finditem ITEM_GROUND_MEMORY
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	finditem ITEM_MEWTWONITE_X
	end

Route134_EventScript_ItemStarPiece:: @ 82910A7
	finditem ITEM_PECHA_BERRY
	end

PetalburgCity_EventScript_ItemMaxRevive:: @ 82910B4
	finditem ITEM_SCOPE_LENS
	end

PetalburgCity_EventScript_ItemEther:: @ 82910C1
	finditem ITEM_DOUSE_DRIVE
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	finditem ITEM_WEPEAR_BERRY
	end

RustboroCity_EventScript_ItemXDefend:: @ 82910DB
	finditem ITEM_SHOCK_DRIVE
	end

LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
	finditem ITEM_HABAN_BERRY
	end

MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
	finditem ITEM_IRON
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	finditem ITEM_POMEG_BERRY
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	finditem ITEM_WEPEAR_BERRY
	end

PetalburgWoods_EventScript_ItemEther:: @ 829111C
	finditem ITEM_FIST_PLATE
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	finditem ITEM_RED_SCARF
	end

RusturfTunnel_EventScript_ItemPokeBall:: @ 8291136
	finditem ITEM_IRON_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther:: @ 8291143
	finditem ITEM_LATIOSITE
	end

GraniteCave_1F_EventScript_ItemEscapeRope:: @ 8291150
	finditem ITEM_WATER_GEM
	end

GraniteCave_B1F_EventScript_ItemPokeBall:: @ 829115D
	finditem ITEM_SEA_INCENSE
	end

GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
	finditem ITEM_WOOD_MAIL
	end

GraniteCave_B2F_EventScript_ItemRareCandy:: @ 8291177
	finditem ITEM_LUCK_INCENSE
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	finditem ITEM_X_ACCURACY
	end

FieryPath_EventScript_ItemFireStone:: @ 8291191
	finditem ITEM_GENGARITE
	end

FieryPath_EventScript_ItemTM06:: @ 829119E
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal:: @ 82911B8
	finditem ITEM_BRIGHT_POWDER
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone:: @ 82911C5
	finditem ITEM_BEEDRILLITE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP:: @ 82911D2
	finditem ITEM_ROCKY_HELMET
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraRope:: @ 82911EC
	finditem ITEM_FLYING_GEM
	end

NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
	finditem ITEM_EJECT_BUTTON
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	finditem ITEM_RINDO_BERRY
	end

NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
	finditem ITEM_ZAP_PLATE
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	finditem ITEM_PEARL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	finditem ITEM_THICK_CLUB
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
	finditem ITEM_GARDEVOIRITE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	finditem ITEM_ROWAP_BERRY
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	finditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
	finditem ITEM_LATIASITE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	finditem ITEM_LIFE_ORB
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
	finditem ITEM_QUALOT_BERRY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	finditem ITEM_BUG_MEMORY
	end

SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
	finditem ITEM_HARBOR_MAIL
	end

SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
	finditem ITEM_GENIUS_WING
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	finditem ITEM_QUICK_CLAW
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	finditem ITEM_BIG_ROOT
	end

MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
	finditem ITEM_RED_SCARF
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	finditem ITEM_X_ATTACK
	end

MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
	finditem ITEM_NANAB_BERRY
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
	finditem ITEM_QUALOT_BERRY
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	finditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	finditem ITEM_SNOWBALL
	end

AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
	finditem ITEM_DOME_FOSSIL
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	finditem ITEM_DURIN_BERRY
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	finditem ITEM_PLUME_FOSSIL
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	finditem ITEM_LEMONADE
	end

Route119_EventScript_ItemNugget:: @ 8291399
	finditem ITEM_ROCK_GEM
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	finditem ITEM_TAMATO_BERRY
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	finditem ITEM_MEDICHAMITE
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	finditem ITEM_ROSE_INCENSE
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
	finditem ITEM_MOON_BALL
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	finditem ITEM_RETRO_MAIL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
	finditem ITEM_SCOPE_LENS
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	finditem ITEM_FLAME_ORB
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	finditem ITEM_LUCK_INCENSE
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	finditem ITEM_LUXURY_BALL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	finditem ITEM_STARDUST
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	finditem ITEM_KEE_BERRY
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	finditem ITEM_SUPER_POTION
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	finditem ITEM_COBA_BERRY
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	finditem ITEM_HELIX_FOSSIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	finditem ITEM_DARK_MEMORY
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	finditem ITEM_TOXIC_PLATE
	end

VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
	finditem ITEM_LIGHT_BALL
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
	finditem ITEM_LUCK_INCENSE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
	finditem ITEM_HEAT_ROCK
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	finditem ITEM_POKE_BALL
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	finditem ITEM_BURN_HEAL
	end

MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
	finditem ITEM_POWER_BAND
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	finditem ITEM_POWER_BAND
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
	finditem ITEM_AMULET_COIN
	end

MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
	finditem ITEM_MAX_ETHER
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	finditem ITEM_FULL_HEAL
	end

MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
	finditem ITEM_POWER_BELT
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
	finditem ITEM_MAX_ELIXIR
	end
